---
title: "ShinyMap"
output: html_document
date: "2024-05-14"
runtime: shiny
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(readr)
library(tidyverse)
library(stringr)
library(dplyr)
library(tmap)
library(ggmap)
library(sf)
library(ggspatial)
library(ggrepel)
library(shiny)
# sample for reading in data that we scraped using Octoparse. 
shoreview_rentals <- read_csv("Shoreview_rentals.csv")
shoreview_buy <- read_csv("Shoreview_buy.csv")
riverside_rentals <- read_csv("Riverside_rentals.csv")
riverside_buy <- read_csv("Riverside_buy.csv")
```

# Data Cleaning and merging

```{r,echo = FALSE, message = FALSE, warning = FALSE}
# clean the FUCK outta shoreview_buy
shoreview_buy <- shoreview_buy %>%
  rename("bedrooms" = "bedroom_s_",
         "bathrooms" = "bathroom_s_",
         ) %>%
  mutate(type = case_when(
    str_detect(status, "[Tt]ownhouse") ~ "Townhouse",
    str_detect(status, "[Hh]ouse") ~ "House",
    str_detect(status, "[Cc]ondo") ~ "Condo",
    str_detect(status, "\\b([Ll]and|[Ll]ot|[Nn]ew)|[Cc]oming\\b") ~ "Misc")) %>%
  mutate(status = "buy",
         price = parse_number(price),
         price = price / 1000) %>%
mutate(address_short = str_extract(address, "^([^,]*)")) %>%
  select(price, bedrooms, bathrooms, square_feet, status, address, type, address_short)

# clean the FUCK outta shoreview_rentals
shoreview_rentals <- shoreview_rentals %>%
  rename("bedrooms" = "bedroom_s_",
         "bathrooms" = "bathroom_s_",
         ) %>%
  mutate(type = case_when(
    str_detect(status, "[Tt]ownhouse") ~ "Townhouse rental",
    str_detect(status, "[Hh]ouse") ~ "House rental"))  %>%
  mutate(type = case_when(
    is.na(type) ~ "Apartment",
    TRUE ~ type
  )) %>%
  mutate(status = "rental",
         price = parse_number(price)) %>%
  mutate(address_short = str_extract(address, "^([^,]*)")) %>%
  select(price, bedrooms, bathrooms, square_feet, status, address, type, address_short)

# clean the FUCK outta riverside_buy 
riverside_buy <- riverside_buy %>%
  rename("bedrooms" = "bedroom_s_",
         "bathrooms" = "bathroom_s_",
         ) %>%
  mutate(price = parse_number(price),
         type = "House") %>%
  mutate(status = "buy") %>%
  mutate(address_short = str_extract(address, "^([^,]*)")) %>%
  select(price, bedrooms, bathrooms, square_feet, status, address, type, address_short)

# clean the FUCK outta riverside_rentals 
riverside_rentals <- riverside_rentals %>%
  rename("bedrooms" = "bedroom_s_",
         "bathrooms" = "bathroom_s_",
         ) %>%
  mutate(price = parse_number(price)) %>%
  mutate(type = "Apartment",
         status = "rental") %>%
  mutate(address_short = str_extract(address, "^([^,]*)")) %>%
  select(price, bedrooms, bathrooms, square_feet, status, address, type, address_short)
  
shoreview_full <- rbind(shoreview_buy, shoreview_rentals)
riverside_full <- rbind(riverside_buy, riverside_rentals)
```

# code to implement long and lat into full data sets. 

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# code to access long and lat via google API
register_google(key = "AIzaSyA-CZDgJkk_zG_ULCoS-PosYIQF_ZzwQPs")

# get data prepped for shoreview including lat and long
addresses_shoreview <- shoreview_full  %>%
    select(address)

  coords <- geocode(addresses_shoreview$address)

  data_coords_shoreview <- cbind(shoreview_full, coords) %>%
    st_as_sf(coords = c("lon", "lat"), crs = 4326) %>%
    st_transform(3857)
  
# get data prepped for riverside including lat and long 
addresses_riverside <- riverside_full  %>%
    select(address)

  coords <- geocode(addresses_riverside$address)

  data_coords_riverside <- cbind(riverside_full, coords) %>%
    st_as_sf(coords = c("lon", "lat"), crs = 4326) %>%
    st_transform(3857)  

```

# Function to plot map data. 

```{r, echo = FALSE, message = FALSE, warning = FALSE}
plot_map<- function(data, rentBuy, size_variable, color_variable, label_size, show_labels){
  data_small <- data %>%
    drop_na(c(.data[[size_variable]], .data[[color_variable]])) 
  
  if(show_labels){
    map <- data %>% 
    filter(status == rentBuy) %>%
    ggplot() +
    annotation_map_tile(type = "osm", zoomin = 0, progress = "none") +
    geom_sf(aes(size = .data[[size_variable]], color = .data[[color_variable]]), alpha = 0.7) +
    geom_label_repel(
      aes(label = address_short, x = st_coordinates(geometry)[,1], y = st_coordinates(geometry)[,2]), # gets coordinates from an otherwise intricate column. 
      size = label_size, box.padding = 0.25, point.padding = 0.3, max.overlaps = Inf
    ) +
    labs(
      size = size_variable,
      color = color_variable,
      title = paste("Housing - ", rentBuy),
      x = "",
      y ="",
    ) +
    theme(
      axis.text.x = element_blank(),   
      axis.text.y = element_blank(),
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(), 
    )
  }
  
  if(show_labels == FALSE){
  map <- data %>% 
    filter(status == rentBuy) %>%
    ggplot() +
    annotation_map_tile(type = "osm", zoomin = 0, progress = "none") +
    geom_sf(aes(size = .data[[size_variable]], color = .data[[color_variable]]), alpha = 0.7) +
    labs(
      size = size_variable,
      color = color_variable,
      title = paste("Housing - ", rentBuy),
      x = "",
      y ="",
    ) +
    theme(
      axis.text.x = element_blank(),   
      axis.text.y = element_blank(),
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(), 
    )
  }
  return(map)
}
```



```{r, echo = FALSE}
library(shiny)

ui <- fluidPage(
  titlePanel("Adjustable Plot Example"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("color", label = "Color Variable", choices = c("price", "square_feet", "bedrooms", "bathrooms", "type")),
      selectInput("size", label = "Size Variable", choices = c("price", "square_feet", "bedrooms", "bathrooms")),
      selectInput("RentBuy", label = "Rental / For Sale", choices = c("buy", "rental")),
      sliderInput("Label_size", label = "Label Size", min = 1.0, max = 5.0, value = 1.5, step = 0.5),
      checkboxInput("show_labels", label = "Show Labels", value = TRUE)
    ),
    mainPanel(
      plotOutput("plotID", width = "100%", height = "600px")
    )
  )
)

server <- function(input, output, session) {
  output$plotID <- renderPlot({
    plot_map(data_coords_shoreview, rentBuy = input$RentBuy, size_variable = input$size, color_variable = input$color, label_size = input$Label_size, show_labels = input$show_labels)
  })
}

shinyApp(ui = ui, server = server)
```


